### ISSUE TITLE
toggle markdown checkbox status when preview checkbox clicked

### ISSUE THREAD

**Issue by klokie** [jasonrudolph/toggle-markdown-task#2]
Hi, I don't know if it's possible with the current version of the markdown preview, but I think it would be amazing if the markdown checkbox (`[x]`) could be toggled in sync with the preview checkbox. Thoughts?

**Comment by jasonrudolph** [comment]
@klokie: I think I understand what you're suggesting, but let me try to restate it to be sure:

As shown in the [demo gif in the README](https://github.com/jasonrudolph/toggle-markdown-task/tree/12cef8d7e1793d3758f719247d3c06dc84807947#toggle-markdown-task-an-atom-package), when you toggle completion of a task in a Markdown file, that change is automatically reflected in the [preview pane](https://github.com/atom/markdown-preview). That works today. You would like the syncing to work in the other direction as well. In other words, when you click on a checkbox for a task in the preview pane, you would like the Markdown file to get updated to reflect that you've completed that task. Am I understanding correctly?

If so, I think that would be cool. https://github.com/atom/markdown-preview/issues/108 is tracking this feature request in the [markdown-preview](https://github.com/atom/markdown-preview) package, so I'm going to close this issue.

> Change the .md file when a checkbox change is triggered in the Preview and check/uncheck them. -- https://github.com/atom/markdown-preview/issues/108#issue-38070199

**Comment by klokie** [comment]
Yes, that's exactly it. :dart:  Thanks so much for your reply!
