### ISSUE TITLE
What do this package?

### ISSUE THREAD

**Issue by janstieler** [jasonrudolph/toggle-markdown-task#3]
Hi,
can you explain me what your package especially do?

Kind regards

**Comment by jasonrudolph** [comment]
When you're editing a markdown file in Atom, and your file includes [a task list](https://help.github.com/articles/about-task-lists/#creating-task-lists), this package provides a [command to toggle the status of the task](https://github.com/jasonrudolph/toggle-markdown-task/blob/b6fcb1c5cacba7317fb0a5c1adb42249fa44b0d8/README.md#toggle-markdown-task-an-atom-package). In other words, if the task is currently *incomplete*, the command will mark the task as *complete*. If the task is currently *complete*, the command will mark the task as *incomplete*.

I recommend [setting up a keyboard shortcut](https://github.com/jasonrudolph/toggle-markdown-task/blob/b6fcb1c5cacba7317fb0a5c1adb42249fa44b0d8/README.md#bring-your-own-keymap) to trigger the package's `toggle-markdown-task:toggle` command.

I hope this helps.
