### ISSUE TITLE
Checkboxes using other bullet characters

### ISSUE THREAD

**Issue by arcandio** [jasonrudolph/toggle-markdown-task#4]
As far as I know, at least `*` is accepted in Atom.io as a valid bullet character in addition to `-` and I think `+`, but the plugin doesn't toggle checkboxes on `*` bullets, only on `-` bullets.

* [ ] Test `*` GFM Checkbox
- [ ] Test `-` GFM Checkbox
+ [ ] Test `+` GFM Checkbox

All three seem to render properly in GFM.

**Comment by jasonrudolph** [comment]
@arcandio: Thanks for logging this. :bow: 

[v0.6.0](https://github.com/jasonrudolph/toggle-markdown-task/releases/tag/v0.6.0) adds support for [tasks that begin with an asterisk (`*`)](https://github.com/jasonrudolph/toggle-markdown-task/blob/73a23482b092b9dadc250db7b23f9e9c1a83eed9/spec/toggle-markdown-task-spec.coffee#L113-L123). 

I've never seen anyone use a plus sign (`+`) for a GitHub-flavored markdown task. If that's something that you're seeing commonly used, please share some links to communities that prefer that markdown format, and I'll can add support for that syntax.

**Comment by arcandio** [comment]
@jasonrudolph I don't know that I've seen it a lot, but I wanted to add it for the sake of completeness, since it renders properly here in Github, which says to me that it's valid in GFM. Thanks for the update!
